### ISSUE TITLE
IRC chatter?

### ISSUE THREAD

**Issue by SketchNI** [PHPJubilee/Project#6]
Is there an irc server/channel for phpjubilee? I think it would be handy to have for teams to communicate with each other. I'd be willing to provide a server for running ircd if you want to stay away from freenode etc.

**Comment by JordanRL** [comment]
I created a gitter.im channel, but we could also do an IRC server/channel possibly.

We will certainly need a way to have rapid communication. If you would like to provide an IRC server than I'm more than happy to accept if people would prefer to use IRC. I'm also fine with freenode.

The only reason I would shy away from it, is that it's probably more beneficial for the devs involved, as far as preparing them with skills they might encounter in the workplace, to use either gitter, slack or hipchat.

**Comment by SketchNI** [comment]
I've never used gitter or slack but I really like hipchat. 

A pro for hipchat would be to have a couple of scripts on a server that github can ping that will alert devs in each team when a new issue/commit etc is made which will nicely keep everything in one place

**Comment by JordanRL** [comment]
That exists and is already set up in gitter, and slack has that feature as well.

gitter uses your github OAuth login, so there's no real "sign up" process.

**Comment by SketchNI** [comment]
I've had a little playaround with gitter and it's quite a bit more advanced than hipchat, especially the sidebar separating activity from the chat. Good call with that!
